// MESLEKLER SERİSİ — güncel ve eski tüm meslekler, eksiksiz
// Her meslek: sahne + görsel + karakter görseli + pratik diyalog (AI her dilde)
// Koşullar: her dil kendi aksanıyla Türkçe + orijinal telafuz, A1-C1, fotoğraflı

import { SceneDef } from "@/lib/scenes";

export const PROFESSION_SCENES: SceneDef[] = [
  // Modern — Teknoloji
  { id: "meslek-yazilimci", category: "meslek", categoryEmoji: "👔", title: "Yazılım Geliştirici", emoji: "💻", location: "Ofis — Yazılım", description: "Kod yaz, bug düzelt, toplantıda sunum yap, iş arkadaşından yardım iste.", npc: { name: "Yazılımcı Ece", role: "Yazılım Geliştirici", emoji: "💻" }, photo: "/scenes/is-ofis.jpg", xp: 100, examples: ["Bug'ı düzeltir misin?", "Kodu gönderir misin?", "Toplantı kaçta?"] },
  { id: "meslek-veri", category: "meslek", categoryEmoji: "👔", title: "Veri Bilimcisi", emoji: "📊", location: "Ofis — Veri", description: "Veri analiz et, grafik göster, rapor yaz.", npc: { name: "Veri Uzmanı", role: "Veri Bilimcisi", emoji: "📊" }, photo: "/scenes/is-ofis.jpg", xp: 100, examples: ["Veriyi analiz eder misin?", "Grafiği gösterir misin?", "Raporu yazar mısın?"] },
  { id: "meslek-tasarimci", category: "meslek", categoryEmoji: "👔", title: "Grafik Tasarımcı", emoji: "🎨", location: "Stüdyo — Tasarım", description: "Logo tasarla, renk seç, müşteriyle konuş.", npc: { name: "Tasarımcı", role: "Grafik Tasarımcı", emoji: "🎨" }, photo: "/scenes/muze.jpg", xp: 90, examples: ["Logo yapar mısın?", "Renk seçer misin?", "Tasarımı beğendin mi?"] },
  { id: "meslek-pazarlama", category: "meslek", categoryEmoji: "👔", title: "Pazarlama Uzmanı", emoji: "📢", location: "Ofis — Pazarlama", description: "Kampanya anlat, müşteri ikna et, sunum yap.", npc: { name: "Pazarlamacı", role: "Pazarlama Uzmanı", emoji: "📢" }, photo: "/scenes/is-ofis.jpg", xp: 95, examples: ["Kampanyayı anlatır mısın?", "Müşteriyi ikna eder misin?", "Sunum yapar mısın?"] },

  // Sağlık — zaten var ama meslek serisine ekle
  { id: "meslek-doktor", category: "meslek", categoryEmoji: "👔", title: "Doktor", emoji: "👨‍⚕️", location: "Hastane — Muayene", description: "Hastayı muayene et, teşhis koy, reçete yaz.", npc: { name: "Dr. Miller", role: "Doktor", emoji: "👨‍⚕️" }, photo: "/scenes/hastane.jpg", xp: 100, examples: ["Nereniz ağrıyor?", "Reçete yazar mısınız?", "Tahlil yaptırır mısınız?"] },
  { id: "meslek-hemsire", category: "meslek", categoryEmoji: "👔", title: "Hemşire", emoji: "👩‍⚕️", location: "Hastane — Servis", description: "İlaç ver, pansuman yap, hasta takibi yap.", npc: { name: "Hemşire Lisa", role: "Hemşire", emoji: "👩‍⚕️" }, photo: "/scenes/hastane.jpg", xp: 90, examples: ["İlacınızı veriyorum", "Pansuman yapar mısınız?", "Ateşinizi ölçeyim mi?"] },
  { id: "meslek-eczaci", category: "meslek", categoryEmoji: "👔", title: "Eczacı", emoji: "💊", location: "Eczane — Banko", description: "İlaç ver, doz anlat, prospektüs ver.", npc: { name: "Eczacı", role: "Eczacı", emoji: "💊" }, photo: "/scenes/hastane.jpg", xp: 85, examples: ["Günde kaç kez alacağım?", "Yan etkisi var mı?", "Reçeteniz var mı?"] },
  { id: "meslek-disci", category: "meslek", categoryEmoji: "👔", title: "Diş Hekimi", emoji: "🦷", location: "Klinik — Diş", description: "Dişi muayene et, dolgu yap, röntgen çek.", npc: { name: "Diş Hekimi", role: "Dişçi", emoji: "🦷" }, photo: "/scenes/disci.jpg", xp: 85, examples: ["Dişiniz çürümüş", "Röntgen çekelim mi?", "Dolgu yapacağım"] },
  { id: "meslek-psikolog", category: "meslek", categoryEmoji: "👔", title: "Psikolog", emoji: "🧠", location: "Klinik — Terapi", description: "Danışanı dinle, tavsiye ver, seans yap.", npc: { name: "Psikolog", role: "Psikolog", emoji: "🧠" }, photo: "/scenes/hastane.jpg", xp: 90, examples: ["Nasıl hissediyorsunuz?", "Anlatır mısınız?", "Nefes egzersizi yapalım mı?"] },
  { id: "meslek-veteriner", category: "meslek", categoryEmoji: "👔", title: "Veteriner", emoji: "🐾", location: "Klinik — Veteriner", description: "Hayvanı muayene et, aşı yap, mama öner.", npc: { name: "Veteriner", role: "Veteriner", emoji: "🐾" }, photo: "/scenes/hastane.jpg", xp: 85, examples: ["Kedim hasta", "Aşı yapar mısınız?", "Mama önerir misiniz?"] },

  // Eğitim
  { id: "meslek-ogretmen", category: "meslek", categoryEmoji: "👔", title: "Öğretmen", emoji: "👩‍🏫", location: "Okul — Sınıf", description: "Ders anlat, ödev ver, soru sor.", npc: { name: "Öğretmen Zeynep", role: "Öğretmen", emoji: "👩‍🏫" }, photo: "/scenes/universite.jpg", xp: 85, examples: ["Ödevinizi yaptınız mı?", "Tahtaya bakar mısınız?", "Soru sorabilir miyim?"] },
  { id: "meslek-profesor", category: "meslek", categoryEmoji: "👔", title: "Profesör", emoji: "👨‍🏫", location: "Üniversite — Amfi", description: "Konferans ver, makale yaz, öğrenci danıştır.", npc: { name: "Prof. Johnson", role: "Profesör", emoji: "👨‍🏫" }, photo: "/scenes/universite.jpg", xp: 95, examples: ["Makalenizi okudum", "Danışmanlık alabilir miyim?", "Konferans ne zaman?"] },
  { id: "meslek-kutuphaneci", category: "meslek", categoryEmoji: "👔", title: "Kütüphaneci", emoji: "📚", location: "Kütüphane — Banko", description: "Kitap ödünç ver, sessiz ol de.", npc: { name: "Kütüphaneci", role: "Kütüphaneci", emoji: "📚" }, photo: "/scenes/kutuphane.jpg", xp: 80, examples: ["Kitap ödünç alabilir miyim?", "Sessiz olur musunuz?", "Üyelik kartınız var mı?"] },

  // Hizmet — güncel
  { id: "meslek-garson", category: "meslek", categoryEmoji: "👔", title: "Garson", emoji: "👨‍🍳", location: "Restoran — Masa", description: "Sipariş al, servis yap, hesap getir.", npc: { name: "Garson Emre", role: "Garson", emoji: "👨‍🍳" }, photo: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 85, examples: ["Sipariş alabilir miyim?", "Servis yapar mısınız?", "Hesap lütfen"] },
  { id: "meslek-barista", category: "meslek", categoryEmoji: "👔", title: "Barista", emoji: "☕", location: "Kafe — Bar", description: "Kahve yap, latte art yap, sipariş al.", npc: { name: "Barista", role: "Barista", emoji: "☕" }, photo: "/scenes/berber.jpg", xp: 80, examples: ["Latte yapar mısınız?", "Filtre kahve var mı?", "Kahveniz hazır"] },
  { id: "meslek-berber", category: "meslek", categoryEmoji: "👔", title: "Berber", emoji: "💈", location: "Berber — Koltuk", description: "Saç kes, sakal düzelt, muhabbet et.", npc: { name: "Berber Murat", role: "Berber", emoji: "💈" }, photo: "/scenes/berber.jpg", xp: 80, examples: ["Saçımı kısaltır mısın?", "Sakal tıraşı yapar mısınız?", "Nasıl keseyim?"] },
  { id: "meslek-terzi", category: "meslek", categoryEmoji: "👔", title: "Terzi", emoji: "✂️", location: "Atölye — Terzi", description: "Pantolon kısalt, düğme dik, prova yap.", npc: { name: "Terzi Ayşe", role: "Terzi", emoji: "✂️" }, photo: "/scenes/terzi.jpg", xp: 80, examples: ["Paçayı kısaltır mısın?", "Düğme diker misin?", "Prova ne zaman?"] },
  { id: "meslek-kasap", category: "meslek", categoryEmoji: "👔", title: "Kasap", emoji: "🥩", location: "Kasap — Tezgah", description: "Et kes, tart, paketle.", npc: { name: "Kasap Ali", role: "Kasap", emoji: "🥩" }, photo: "/scenes/kasap.jpg", xp: 80, examples: ["Yarım kilo kıyma alayım", "Taze mi etler?", "Paketler misiniz?"] },
  { id: "meslek-firinci", category: "meslek", categoryEmoji: "👔", title: "Fırıncı", emoji: "🍞", location: "Fırın — Tezgah", description: "Ekmek çıkar, pide yap, sıcak ver.", npc: { name: "Fırıncı", role: "Fırıncı", emoji: "🍞" }, photo: "/scenes/firin.jpg", xp: 80, examples: ["Sıcak ekmek var mı?", "Pide yapar mısınız?", "Kaç lira?"] },

  // Esnaf — güncel ve eski
  { id: "meslek-bakkal", category: "meslek", categoryEmoji: "👔", title: "Bakkal", emoji: "🏪", location: "Bakkal — Tezgah", description: "Ekmek, süt ver, veresiye yaz.", npc: { name: "Bakkal Amca", role: "Bakkal", emoji: "🏪" }, photo: "/scenes/kasap.jpg", xp: 75, examples: ["Ekmek verir misin?", "Veresiye yazar mısın?", "Borcum ne kadar?"] },
  { id: "meslek-manav", category: "meslek", categoryEmoji: "👔", title: "Manav", emoji: "🥦", location: "Manav — Tezgah", description: "Sebze tart, meyve seç, poşet ver.", npc: { name: "Manav", role: "Manav", emoji: "🥦" }, photo: "/scenes/kasap.jpg", xp: 75, examples: ["Domates ne kadar?", "Taze mi?", "Poşet verir misin?"] },

  // Usta — güncel ve eski
  { id: "meslek-marangoz", category: "meslek", categoryEmoji: "👔", title: "Marangoz", emoji: "🪵", location: "Atölye — Marangoz", description: "Mobilya yap, tahta kes, vernikle.", npc: { name: "Marangoz", role: "Marangoz", emoji: "🪵" }, photo: "/scenes/is-fabrika.jpg", xp: 85, examples: ["Masa yapar mısın?", "Tahtayı keser misin?", "Vernik ne zaman kurur?"] },
  { id: "meslek-elektrikci", category: "meslek", categoryEmoji: "👔", title: "Elektrikçi", emoji: "💡", location: "Ev — Elektrik", description: "Prizi tamir et, kablo çek, sigorta değiştir.", npc: { name: "Elektrikçi", role: "Elektrikçi", emoji: "💡" }, photo: "/scenes/is-fabrika.jpg", xp: 85, examples: ["Prizi tamir eder misin?", "Kablo çeker misin?", "Sigorta attı"] },
  { id: "meslek-tesisatci", category: "meslek", categoryEmoji: "👔", title: "Tesisatçı", emoji: "🔧", location: "Ev — Tesisat", description: "Musluk tamir et, boru döşe, su kaçağı bul.", npc: { name: "Tesisatçı", role: "Tesisatçı", emoji: "🔧" }, photo: "/scenes/is-fabrika.jpg", xp: 85, examples: ["Musluk akıyor", "Boru döşer misin?", "Su kaçağı var"] },
  { id: "meslek-boyaci", category: "meslek", categoryEmoji: "👔", title: "Boyacı", emoji: "🎨", location: "Ev — Boya", description: "Duvar boya, badana yap, renk seç.", npc: { name: "Boyacı", role: "Boyacı", emoji: "🎨" }, photo: "/scenes/muze.jpg", xp: 80, examples: ["Duvarı boyar mısın?", "Hangi renk olsun?", "Badana ne kadar?"] },
  { id: "meslek-kaynakci", category: "meslek", categoryEmoji: "👔", title: "Kaynakçı", emoji: "🔥", location: "Atölye — Kaynak", description: "Demir kayna, iskele kur, kask tak.", npc: { name: "Kaynakçı", role: "Kaynakçı", emoji: "🔥" }, photo: "/scenes/is-fabrika.jpg", xp: 85, examples: ["Demiri kaynatır mısın?", "Kask takar mısın?", "İskele sağlam mı?"] },

  // Eski meslekler — eksiksiz
  { id: "meslek-demirci", category: "meslek", categoryEmoji: "👔", title: "Demirci", emoji: "🔨", location: "Demirci — Ocak", description: "Demir döv, nal yap, örs çal.", npc: { name: "Demirci", role: "Demirci", emoji: "🔨" }, photo: "/scenes/is-fabrika.jpg", xp: 85, examples: ["Nal yapar mısın?", "Demiri döver misin?", "Örsün nerede?"] },
  { id: "meslek-comlekci", category: "meslek", categoryEmoji: "👔", title: "Çömlekçi", emoji: "🏺", location: "Atölye — Çömlek", description: "Çamur yoğur, çömlek yap, fırınla.", npc: { name: "Çömlekçi", role: "Çömlekçi", emoji: "🏺" }, photo: "/scenes/muze.jpg", xp: 80, examples: ["Çömlek yapar mısın?", "Çamuru yoğurur musun?", "Fırınlar mısın?"] },
  { id: "meslek-dokumaci", category: "meslek", categoryEmoji: "👔", title: "Dokumacı", emoji: "🧵", location: "Atölye — Dokuma", description: "İplik eğir, kilim doku, tezgah kur.", npc: { name: "Dokumacı", role: "Dokumacı", emoji: "🧵" }, photo: "/scenes/muze.jpg", xp: 80, examples: ["Kilim dokur musun?", "İpliği eğirir misin?", "Tezgah nasıl kurulur?"] },
  { id: "meslek-kunduraci", category: "meslek", categoryEmoji: "👔", title: "Kunduracı", emoji: "👞", location: "Dükkan — Kundura", description: "Ayakkabı tamir et, taban dik, boya yap.", npc: { name: "Kunduracı", role: "Kunduracı", emoji: "👞" }, photo: "/scenes/terzi.jpg", xp: 80, examples: ["Ayakkabım söküldü", "Taban diker misin?", "Boyar mısın?"] },
  { id: "meslek-bakirci", category: "meslek", categoryEmoji: "👔", title: "Bakırcı", emoji: "🥘", location: "Çarşı — Bakır", description: "Bakır döv, tencere yap, kalayla.", npc: { name: "Bakırcı", role: "Bakırcı", emoji: "🥘" }, photo: "/scenes/is-fabrika.jpg", xp: 80, examples: ["Bakırı döver misin?", "Tencere yapar mısın?", "Kalaylar mısın?"] },
  { id: "meslek-semerci", category: "meslek", categoryEmoji: "👔", title: "Semerci", emoji: "🐴", location: "Atölye — Semer", description: "Semer yap, deri dik, at donat.", npc: { name: "Semerci", role: "Semerci", emoji: "🐴" }, photo: "/scenes/is-fabrika.jpg", xp: 80, examples: ["Semer yapar mısın?", "Deri diker misin?", "Atı donatır mısın?"] },
  { id: "meslek-sarac", category: "meslek", categoryEmoji: "👔", title: "Saraç", emoji: "🐎", location: "Dükkan — Saraç", description: "Eyer yap, kayış dik, deri işle.", npc: { name: "Saraç", role: "Saraç", emoji: "🐎" }, photo: "/scenes/terzi.jpg", xp: 80, examples: ["Eyer yapar mısın?", "Kayışı diker misin?", "Deri işler misin?"] },
  { id: "meslek-kalayci", category: "meslek", categoryEmoji: "👔", title: "Kalaycı", emoji: "✨", location: "Sokak — Kalay", description: "Bakır kalayla, ateş yak, gezerek bağır.", npc: { name: "Kalaycı", role: "Kalaycı", emoji: "✨" }, photo: "/scenes/is-fabrika.jpg", xp: 80, examples: ["Kalay yapar mısın?", "Ateşi yakar mısın?", "Bakır kalaylar mısın?"] },
  { id: "meslek-kececi", category: "meslek", categoryEmoji: "👔", title: "Keçeci", emoji: "🐑", location: "Atölye — Keçe", description: "Yün döv, keçe yap, şapka dik.", npc: { name: "Keçeci", role: "Keçeci", emoji: "🐑" }, photo: "/scenes/muze.jpg", xp: 80, examples: ["Keçe yapar mısın?", "Yünü döver misin?", "Şapka diker misin?"] },

  // Diğer güncel meslekler
  { id: "meslek-ciftci", category: "meslek", categoryEmoji: "👔", title: "Çiftçi", emoji: "🚜", location: "Tarla — Çiftlik", description: "Tarla sür, tohum ek, hasat yap.", npc: { name: "Çiftçi", role: "Çiftçi", emoji: "🚜" }, photo: "/scenes/park.jpg", xp: 80, examples: ["Tarla sürer misin?", "Tohum eker misin?", "Hasat ne zaman?"] },
  { id: "meslek-bahcivan", category: "meslek", categoryEmoji: "👔", title: "Bahçıvan", emoji: "🌱", location: "Bahçe — Park", description: "Çiçek ek, ağaç buda, çim biç.", npc: { name: "Bahçıvan", role: "Bahçıvan", emoji: "🌱" }, photo: "/scenes/park.jpg", xp: 75, examples: ["Çiçek eker misin?", "Ağacı budar mısın?", "Çimi biçer misin?"] },
  { id: "meslek-balikci", category: "meslek", categoryEmoji: "👔", title: "Balıkçı", emoji: "🎣", location: "Liman — Tekne", description: "Ağ at, balık tut, ağ tamir et.", npc: { name: "Balıkçı", role: "Balıkçı", emoji: "🎣" }, photo: "https://images.pexels.com/photos/294674/pexels-photo-294674.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 75, examples: ["Ağ atar mısın?", "Balık tuttun mu?", "Ağı tamir eder misin?"] },
  { id: "meslek-itfaiyeci", category: "meslek", categoryEmoji: "👔", title: "İtfaiyeci", emoji: "🚒", location: "İtfaiye — Merkez", description: "Yangın söndür, merdiven aç, kedi kurtar.", npc: { name: "İtfaiyeci", role: "İtfaiyeci", emoji: "🚒" }, photo: "/scenes/hastane.jpg", xp: 90, examples: ["Yangın var!", "Merdiveni açar mısın?", "Kedi kurtarır mısın?"] },
  { id: "meslek-pilot", category: "meslek", categoryEmoji: "👔", title: "Pilot", emoji: "✈️", location: "Kokpit — Uçak", description: "Uçağı uçur, kuleyle konuş, iniş yap.", npc: { name: "Pilot", role: "Pilot", emoji: "✈️" }, photo: "https://images.pexels.com/photos/723009/pexels-photo-723009.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 100, examples: ["Uçuş kaçta?", "Kuleyle konuşur musun?", "İniş yapar mısın?"] },
  { id: "meslek-ascı", category: "meslek", categoryEmoji: "👔", title: "Aşçı", emoji: "👨‍🍳", location: "Mutfak — Ocak", description: "Yemek yap, tarif ver, ocak yak.", npc: { name: "Aşçı", role: "Aşçı", emoji: "👨‍🍳" }, photo: "/scenes/ev-mutfak.jpg", xp: 85, examples: ["Yemek yapar mısın?", "Tarif verir misin?", "Ocağı yakar mısın?"] },
  { id: "meslek-sanatci", category: "meslek", categoryEmoji: "👔", title: "Sanatçı", emoji: "🎨", location: "Atölye — Sanat", description: "Resim yap, heykel yont, sergi aç.", npc: { name: "Sanatçı", role: "Sanatçı", emoji: "🎨" }, photo: "/scenes/muze.jpg", xp: 85, examples: ["Resim yapar mısın?", "Heykel yontar mısın?", "Sergi ne zaman?"] },
  { id: "meslek-muzisyen", category: "meslek", categoryEmoji: "👔", title: "Müzisyen", emoji: "🎵", location: "Sahne — Müzik", description: "Enstrüman çal, şarkı söyle, prova yap.", npc: { name: "Müzisyen", role: "Müzisyen", emoji: "🎵" }, photo: "/scenes/muze.jpg", xp: 85, examples: ["Gitar çalar mısın?", "Şarkı söyler misin?", "Prova yapalım mı?"] },
  { id: "meslek-oyuncu", category: "meslek", categoryEmoji: "👔", title: "Oyuncu", emoji: "🎭", location: "Set — Kamera", description: "Replik söyle, sahne çek, prova yap.", npc: { name: "Oyuncu", role: "Oyuncu", emoji: "🎭" }, photo: "/scenes/tiyatro.jpg", xp: 85, examples: ["Repliğimi söyler misin?", "Sahne çekelim mi?", "Prova yapalım mı?"] },
  { id: "meslek-fotografci", category: "meslek", categoryEmoji: "👔", title: "Fotoğrafçı", emoji: "📸", location: "Stüdyo — Fotoğraf", description: "Fotoğraf çek, poz ver, ışık ayarla.", npc: { name: "Fotoğrafçı", role: "Fotoğrafçı", emoji: "📸" }, photo: "/scenes/muze.jpg", xp: 85, examples: ["Fotoğraf çeker misin?", "Poz verir misin?", "Işığı ayarlar mısın?"] },
  { id: "meslek-gazeteci", category: "meslek", categoryEmoji: "👔", title: "Gazeteci", emoji: "📰", location: "Haber — Sokak", description: "Röportaj yap, haber yaz, fotoğraf çek.", npc: { name: "Gazeteci", role: "Gazeteci", emoji: "📰" }, photo: "/scenes/is-ofis.jpg", xp: 90, examples: ["Röportaj yapar mısın?", "Haber yazar mısın?", "Fotoğraf çeker misin?"] },
  { id: "meslek-avukat", category: "meslek", categoryEmoji: "👔", title: "Avukat", emoji: "⚖️", location: "Mahkeme — Duruşma", description: "Savunma yap, dilekçe yaz, müvekkille konuş.", npc: { name: "Avukat", role: "Avukat", emoji: "⚖️" }, photo: "/scenes/hastane.jpg", xp: 95, examples: ["Savunma yapar mısınız?", "Dilekçe yazar mısınız?", "Müvekkilimle görüşeceğim"] },
  { id: "meslek-hakim", category: "meslek", categoryEmoji: "👔", title: "Hakim", emoji: "⚖️", location: "Mahkeme — Kürsü", description: "Duruşma yönet, karar ver, cübbe giy.", npc: { name: "Hakim", role: "Hakim", emoji: "⚖️" }, photo: "/scenes/hastane.jpg", xp: 95, examples: ["Karar veriyorum", "Sessizlik lütfen", "Duruşma başlasın"] },
];
