// KAPSAMLI ORTAMLAR — 12 kategori, 60+ sahne, her ortam her olasılık
// Her sahne: AI kişiliği + fotoğraf + pratik diyalog (çatal ver, yumurta çıkar vb.)

export interface SceneDef {
  id: string;
  category: string;
  categoryEmoji: string;
  title: string;
  emoji: string;
  location: string;
  description: string;
  npc: { name: string; role: string; emoji: string };
  secondaryNpc?: { name: string; role: string; emoji: string };
  photo: string;
  xp: number;
  examples: string[]; // pratik örnekler: çatal ver, yumurta çıkar
}

export const CATEGORIES = [
  { key: "ozel", label: "Özel Hayat & Aile", emoji: "🏠", desc: "Mahrem, samimi, argo-şiveli" },
  { key: "is", label: "İş & Profesyonel", emoji: "💼", desc: "Resmi, hiyerarşik, terminoloji" },
  { key: "egitim", label: "Eğitim & Okul", emoji: "🎓", desc: "Akademik, öğrenme" },
  { key: "kamusal", label: "Kamusal & Alışveriş", emoji: "🛒", desc: "Günlük zorunlu" },
  { key: "resmi", label: "Resmi Kurum & Bürokrasi", emoji: "🏛️", desc: "Kalıp, resmi" },
  { key: "saglik", label: "Sağlık & Hastane", emoji: "🏥", desc: "Endişe, acil" },
  { key: "ulasim", label: "Ulaşım & Seyahat", emoji: "✈️", desc: "Kısa, pratik" },
  { key: "sosyal", label: "Sosyal & Kültürel", emoji: "🎉", desc: "Eğlence, sanat" },
  { key: "spor", label: "Spor & Hobi", emoji: "⚽", desc: "Rekabet, dayanışma" },
  { key: "dini", label: "Dini & Manevi", emoji: "🕌", desc: "Ritüel, sohbet" },
  { key: "dijital", label: "Dijital & Sanal", emoji: "💻", desc: "Yazılı, sesli" },
  { key: "mahalle", label: "Mahalle & Sokak", emoji: "🏘️", desc: "En doğal" },
] as const;

export const ALL_SCENES: SceneDef[] = [
  // 1. ÖZEL HAYAT & AİLE (10 sahne)
  { id: "ev-salon", category: "ozel", categoryEmoji: "🏠", title: "Salon", emoji: "🛋️", location: "Ev — Salon", description: "Koltukta oturuyorsun, kumanda ver, ışığı aç, çay getir gibi günlük istekler.", npc: { name: "Anne Ayşe", role: "Anne", emoji: "👩‍🍳" }, photo: "/scenes/ev-salon.jpg", xp: 80, examples: ["Kumandayı verir misin?", "Işığı açar mısın?", "Çay getirir misin?"] },
  { id: "ev-mutfak", category: "ozel", categoryEmoji: "🏠", title: "Mutfak", emoji: "🍳", location: "Ev — Mutfak", description: "Yemek yapıyorsun: çatal ver, bıçak ver, yumurta çıkar, tuzu uzat.", npc: { name: "Anne Ayşe", role: "Anne", emoji: "👩‍🍳" }, secondaryNpc: { name: "Baba Murat", role: "Baba", emoji: "👨" }, photo: "/scenes/ev-mutfak.jpg", xp: 90, examples: ["Çatal verir misin?", "Bıçak ver", "Yumurta çıkar", "Tuzu uzatır mısın?"] },
  { id: "ev-banyo", category: "ozel", categoryEmoji: "🏠", title: "Banyo", emoji: "🚿", location: "Ev — Banyo", description: "Havlu ver, şampuan uzat, sıcak suyu aç.", npc: { name: "Kardeş Elif", role: "Kız Kardeş", emoji: "👧" }, photo: "https://images.pexels.com/photos/342800/pexels-photo-342800.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 70, examples: ["Havlu verir misin?", "Şampuan nerede?", "Sıcak suyu açar mısın?"] },
  { id: "ev-yatak", category: "ozel", categoryEmoji: "🏠", title: "Yatak Odası", emoji: "🛏️", location: "Ev — Yatak Odası", description: "Yorganı düzelt, perdeyi kapat, alarmı kur.", npc: { name: "Sevgili Elif", role: "Sevgili", emoji: "💕" }, photo: "https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 80, examples: ["Yorganı düzeltir misin?", "Perdeyi kapat", "Alarmı kurar mısın?"] },
  { id: "ev-balkon", category: "ozel", categoryEmoji: "🏠", title: "Balkon", emoji: "🌿", location: "Ev — Balkon", description: "Çiçekleri sula, çamaşırı as, manzara izle.", npc: { name: "Baba Murat", role: "Baba", emoji: "👨" }, photo: "https://images.pexels.com/photos/2116721/pexels-photo-2116721.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 70, examples: ["Çiçekleri sular mısın?", "Çamaşırı asar mısın?", "Hava çok güzel değil mi?"] },
  { id: "ev-bahce", category: "ozel", categoryEmoji: "🏠", title: "Bahçe & Havuz Başı", emoji: "🏊", location: "Ev — Bahçe", description: "Mangalı yak, topu at, havluyu getir.", npc: { name: "Kardeş Can", role: "Erkek Kardeş", emoji: "👦" }, photo: "/scenes/ev-bahce.jpg", xp: 80, examples: ["Topu atar mısın?", "Havluyu getirir misin?", "Mangalı yakalım mı?"] },
  { id: "ev-komsu", category: "ozel", categoryEmoji: "🏠", title: "Komşu Ziyareti", emoji: "🏘️", location: "Komşu — Misafirlik", description: "Kapıyı çal, içeri gir, çay ikram et, sohbet et.", npc: { name: "Komşu Fatma", role: "Komşu", emoji: "👵" }, photo: "https://images.pexels.com/photos/3184183/pexels-photo-3184183.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 90, examples: ["Buyurun, çay içer misiniz?", "Nasılsınız komşu?", "Çocuklar nasıl?"] },
  { id: "ev-buyukanne", category: "ozel", categoryEmoji: "🏠", title: "Büyükanne Evi", emoji: "👵", location: "Büyükanne Evi", description: "Elini öp, börek ye, hatır sor, dua iste.", npc: { name: "Büyükanne", role: "Büyükanne", emoji: "👵" }, photo: "https://images.pexels.com/photos/granny/pexels-photo-granny.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace(" granny"," 6384"), xp: 90, examples: ["Elini öpeyim babaanne", "Börek çok güzel olmuş", "Dua eder misin?"] },
  { id: "ev-garaj", category: "ozel", categoryEmoji: "🏠", title: "Garaj & Kiler", emoji: "🔧", location: "Ev — Garaj", description: "Tornavidayı ver, kutuyu kaldır, arabayı yıka.", npc: { name: "Baba Murat", role: "Baba", emoji: "👨" }, photo: "https://images.pexels.com/photos/4480505/pexels-photo-4480505.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 75, examples: ["Tornavidayı verir misin?", "Kutuyu kaldırır mısın?", "Arabayı yıkayalım mı?"] },
  { id: "ev-yazlik", category: "ozel", categoryEmoji: "🏠", title: "Yazlık / Karavan", emoji: "🏖️", location: "Yazlık — Sahil", description: "Şezlongu aç, güneş kremini sür, denize gidelim.", npc: { name: "Sevgili Elif", role: "Sevgili", emoji: "💕" }, photo: "https://images.pexels.com/photos/1450353/pexels-photo-1450353.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 85, examples: ["Şezlongu açar mısın?", "Güneş kremini sürer misin?", "Denize gidelim mi?"] },

  // 2. İŞ & PROFESYONEL (6 sahne)
  { id: "is-ofis", category: "is", categoryEmoji: "💼", title: "Açık Ofis", emoji: "💻", location: "Ofis — Açık Ofis", description: "Bilgisayarı aç, dosyayı gönder, yazıcıdan çıktı al.", npc: { name: "Müdür Selim", role: "Patron", emoji: "👔" }, photo: "/scenes/is-ofis.jpg", xp: 100, examples: ["Dosyayı gönderir misin?", "Yazıcıdan çıktı alır mısın?", "Toplantı kaçta?"] },
  { id: "is-toplanti", category: "is", categoryEmoji: "💼", title: "Toplantı Salonu", emoji: "📊", location: "Ofis — Toplantı", description: "Sunum yap, fikir belirt, itiraz et, not al.", npc: { name: "Müdür Selim", role: "Patron", emoji: "👔" }, secondaryNpc: { name: "Lena", role: "İş Arkadaşı", emoji: "👩‍💼" }, photo: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 110, examples: ["Fikrimi söyleyebilir miyim?", "Katılmıyorum, çünkü...", "Not alır mısın?"] },
  { id: "is-kantin", category: "is", categoryEmoji: "💼", title: "İş Kantini", emoji: "☕", location: "İş — Çay Odası", description: "Çay koy, dedikodu yap, çay ısmarla.", npc: { name: "Lena", role: "İş Arkadaşı", emoji: "👩‍💼" }, photo: "https://images.pexels.com/photos/canteen/pexels-photo-canteen.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace(" canteen"," 3184296"), xp: 80, examples: ["Çay koyar mısın?", "Dün akşam ne yaptın?", "Çay ısmarlayayım mı?"] },
  { id: "is-fabrika", category: "is", categoryEmoji: "💼", title: "Fabrika / Atölye", emoji: "🏭", location: "Fabrika — Atölye", description: "Baret tak, makineyi çalıştır, vardiya sor.", npc: { name: "Usta Kemal", role: "Usta Başı", emoji: "👷" }, photo: "/scenes/is-fabrika.jpg", xp: 95, examples: ["Baretini takar mısın?", "Makineyi çalıştırır mısın?", "Vardiya kaçta bitiyor?"] },
  { id: "is-magaza", category: "is", categoryEmoji: "💼", title: "Mağaza / Showroom", emoji: "🛍️", location: "Mağaza — Satış", description: "Müşteriye ürün göster, fiyatı söyle, indirim yap.", npc: { name: "Satış Danışmanı", role: "Satış", emoji: "🧑‍💼" }, photo: "https://images.pexels.com/photos/135620/pexels-photo-135620.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 90, examples: ["Bu ürün ne kadar?", "İndirim yapar mısınız?", "Başka rengi var mı?"] },
  { id: "is-fuar", category: "is", categoryEmoji: "💼", title: "Fuar & İş Yemeği", emoji: "🤝", location: "Fuar — Otel Lobisi", description: "Kartvizit ver, iş yemeğinde sipariş ver, uçakta sohbet.", npc: { name: "Partner John", role: "İş Ortağı", emoji: "🤝" }, photo: "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 120, examples: ["Kartvizitimi verebilir miyim?", "İş yemeğine gelir misiniz?", "Uçakta yan yana mıyız?"] },

  // 3. EĞİTİM & OKUL (5 sahne)
  { id: "egitim-sinif", category: "egitim", categoryEmoji: "🎓", title: "Sınıf / Amfi", emoji: "👨‍🏫", location: "Okul — Sınıf", description: "Tahtayı sil, soru sor, ödev ver, söz al.", npc: { name: "Öğretmen Zeynep", role: "Öğretmen", emoji: "👩‍🏫" }, photo: "/scenes/universite.jpg", xp: 85, examples: ["Tahtayı siler misin?", "Soru sorabilir miyim?", "Ödev nedir?"] },
  { id: "egitim-kantin", category: "egitim", categoryEmoji: "🎓", title: "Okul Kantini", emoji: "🥪", location: "Okul — Kantin", description: "Tost al, ayran iste, borç ver, sıra bekle.", npc: { name: "Kantinci Abi", role: "Kantinci", emoji: "🧑‍🍳" }, photo: "https://images.pexels.com/photos/canteen2/pexels-photo-canteen2.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace(" canteen2"," 2983101"), xp: 75, examples: ["Tost alabilir miyim?", "Ayran verir misin?", "Sıra kimde?"] },
  { id: "egitim-kutuphane", category: "egitim", categoryEmoji: "🎓", title: "Kütüphane", emoji: "🤫", location: "Okul — Kütüphane", description: "Fısılda, kitap ödünç al, sessiz ol.", npc: { name: "Ms. Green", role: "Kütüphaneci", emoji: "📚" }, photo: "/scenes/kutuphane.jpg", xp: 80, examples: ["Fısıldar mısın?", "Kitap ödünç alabilir miyim?", "Sessiz olur musun?"] },
  { id: "egitim-yurt", category: "egitim", categoryEmoji: "🎓", title: "Öğrenci Yurdu", emoji: "🛏️", location: "Yurt — Oda", description: "Işığı kapat, çamaşırı yıka, gürültü yapma.", npc: { name: "Oda Arkadaşı", role: "Öğrenci", emoji: "👨‍🎓" }, photo: "https://images.pexels.com/photos/ dorm/pexels-photo-dorm.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  dorm"," 1571359"), xp: 80, examples: ["Işığı kapatır mısın?", "Gürültü yapma lütfen", "Çamaşırhanede yer var mı?"] },
  { id: "egitim-kampus", category: "egitim", categoryEmoji: "🎓", title: "Kampüs", emoji: "🌳", location: "Kampüs — Bahçe", description: "Çimlere otur, gitar çal, ders çalış.", npc: { name: "Kampüs Arkadaşı", role: "Öğrenci", emoji: "🧑‍🎓" }, photo: "https://images.pexels.com/photos/ campus/pexels-photo-campus.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  campus"," 794064"), xp: 75, examples: ["Buraya oturabilir miyim?", "Gitar çalar mısın?", "Ders notun var mı?"] },

  // 4. KAMUSAL & ALIŞVERİŞ (6 sahne)
  { id: "kamusal-market", category: "kamusal", categoryEmoji: "🛒", title: "Market / Manav", emoji: "🥦", location: "Market — Manav", description: "Domates tart, ekmek al, fiş ver.", npc: { name: "Manav Ali", role: "Manav", emoji: "🧑‍🌾" }, photo: "/scenes/kasap.jpg".replace("  market"," 264636"), xp: 80, examples: ["Domates ne kadar?", "Yarım ekmek alayım", "Fiş verir misin?"] },
  { id: "kamusal-avm", category: "kamusal", categoryEmoji: "🛒", title: "AVM", emoji: "🏬", location: "AVM — Giyim Mağazası", description: "Beden sor, kabin nerede, kasa nerede.", npc: { name: "Satış Görevlisi", role: "Mağaza Çalışanı", emoji: "👩‍💼" }, photo: "https://images.pexels.com/photos/ avm/pexels-photo-avm.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  avm","  3965545"), xp: 85, examples: ["Bedeni var mı?", "Kabin nerede?", "Kasa nerede?"] },
  { id: "kamusal-pazar", category: "kamusal", categoryEmoji: "🛒", title: "Pazar Yeri", emoji: "🍅", location: "Pazar — Tezgah", description: "Pazarlık yap, poşet iste, taze mi sor.", npc: { name: "Pazarcı Hasan", role: "Pazarcı", emoji: "🧑‍🌾" }, photo: "/scenes/firin.jpg".replace("  pazar"," 1300972"), xp: 85, examples: ["Pazarlık olur mu?", "Taze mi bunlar?", "Poşet verir misin?"] },
  { id: "kamusal-restoran", category: "kamusal", categoryEmoji: "🛒", title: "Restoran / Meyhane", emoji: "🍽️", location: "Restoran — Masa", description: "Sipariş ver, hesap iste, meze sor.", npc: { name: "Garson Emre", role: "Garson", emoji: "👨‍🍳" }, photo: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 90, examples: ["Meze ne var?", "Hesap lütfen", "Acı sever misiniz?"] },
  { id: "kamusal-kuafor", category: "kamusal", categoryEmoji: "🛒", title: "Berber / Kuaför", emoji: "💈", location: "Berber — Koltuk", description: "Saç kes, sakal düzelt, fön çek, muhabbet et.", npc: { name: "Berber Murat", role: "Berber", emoji: "💈" }, photo: "/scenes/berber.jpg".replace("  barber"," 1319460"), xp: 80, examples: ["Saçımı kısaltır mısın?", "Sakalımı düzeltir misin?", "Nasıl keseyim?"] },
  { id: "kamusal-terzi", category: "kamusal", categoryEmoji: "🛒", title: "Terzi", emoji: "✂️", location: "Terzi — Atölye", description: "Pantolon daralt, düğme dik, prova yap.", npc: { name: "Terzi Ayşe", role: "Terzi", emoji: "✂️" }, photo: "/scenes/terzi.jpg".replace("  tailor","  4623223"), xp: 75, examples: ["Paçayı kısaltır mısın?", "Düğme diker misin?", "Prova ne zaman?"] },

  // 5. RESMİ KURUM & BÜROKRASİ (5 sahne)
  { id: "resmi-belediye", category: "resmi", categoryEmoji: "🏛️", title: "Belediye", emoji: "🏢", location: "Belediye — Nüfus", description: "İkametgah al, dilekçe ver, sıra bekle.", npc: { name: "Memur Selin", role: "Memur", emoji: "👩‍💼" }, photo: "https://images.pexels.com/photos/ belediye/pexels-photo-belediye.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  belediye"," 3184296"), xp: 90, examples: ["İkametgah alabilir miyim?", "Dilekçe nereye verilir?", "Sıra numarası alır mısın?"] },
  { id: "resmi-noter", category: "resmi", categoryEmoji: "🏛️", title: "Noter / Mahkeme", emoji: "⚖️", location: "Noter — Banko", description: "İmza at, vekalet ver, tasdik ettir.", npc: { name: "Noter Bey", role: "Noter", emoji: "⚖️" }, photo: "https://images.pexels.com/photos/ noter/pexels-photo-noter.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  noter","  5668859"), xp: 95, examples: ["İmza atar mısınız?", "Vekalet vereceğim", "Tasdik eder misiniz?"] },
  { id: "resmi-polisi", category: "resmi", categoryEmoji: "🏛️", title: "Polis Karakolu", emoji: "👮", location: "Karakol — Banko", description: "İhbar et, ifade ver, tutanak tut.", npc: { name: "Komiser Ayhan", role: "Polis", emoji: "👮" }, photo: "https://images.pexels.com/photos/ police/pexels-photo-police.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  police","  7534285"), xp: 100, examples: ["İhbar etmek istiyorum", "İfade vereceğim", "Tutanak tutar mısınız?"] },
  { id: "resmi-banka", category: "resmi", categoryEmoji: "🏛️", title: "Banka / PTT", emoji: "🏦", location: "Banka — Gişe", description: "Para çek, havale yap, kargo gönder.", npc: { name: "Gişe Memuru", role: "Banka Görevlisi", emoji: "👨‍💼" }, photo: "https://images.pexels.com/photos/259027/pexels-photo-259027.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800", xp: 90, examples: ["Havale yapmak istiyorum", "Para çekeceğim", "Kargo ne kadar?"] },
  { id: "resmi-vergi", category: "resmi", categoryEmoji: "🏛️", title: "Vergi Dairesi", emoji: "🧾", location: "Vergi Dairesi — Vezne", description: "Borç sor, yapılandır, makbuz al.", npc: { name: "Vezne Memuru", role: "Memur", emoji: "🧾" }, photo: "https://images.pexels.com/photos/ vergi/pexels-photo-vergi.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  vergi","  6863181"), xp: 85, examples: ["Borcum ne kadar?", "Yapılandırma var mı?", "Makbuz verir misiniz?"] },

  // 6. SAĞLIK & HASTANE (5 sahne)
  { id: "saglik-muayene", category: "saglik", categoryEmoji: "🏥", title: "Muayenehane", emoji: "🩺", location: "Klinik — Muayene", description: "Ateşin var, boğazın ağrıyor, reçete yaz.", npc: { name: "Dr. Elif", role: "Doktor", emoji: "👩‍⚕️" }, photo: "/scenes/hastane.jpg".replace("  muayene","  40568"), xp: 95, examples: ["Boğazım ağrıyor", "Ateşim var", "Reçete yazar mısınız?"] },
  { id: "saglik-acil", category: "saglik", categoryEmoji: "🏥", title: "Acil Servis", emoji: "🚨", location: "Hastane — Acil", description: "Yakınını bekle, fısır fısır konuş, doktor bekle.", npc: { name: "Hemşire", role: "Hemşire", emoji: "👩‍⚕️" }, photo: "https://images.pexels.com/photos/ acil/pexels-photo-acil.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  acil","  263402"), xp: 100, examples: ["Durumu nasıl?", "Doktor ne dedi?", "Bekleme salonu nerede?"] },
  { id: "saglik-eczane", category: "saglik", categoryEmoji: "🏥", title: "Eczane", emoji: "💊", location: "Eczane — Banko", description: "İlaç al, prospektüs sor, doz sor.", npc: { name: "Eczacı", role: "Eczacı", emoji: "💊" }, photo: "/scenes/hastane.jpg".replace("  eczane","  139398"), xp: 85, examples: ["İlacım var mı?", "Günde kaç kez alacağım?", "Yan etkisi var mı?"] },
  { id: "saglik-disci", category: "saglik", categoryEmoji: "🏥", title: "Dişçi", emoji: "🦷", location: "Diş Kliniği — Koltuk", description: "Dişin ağrıyor, dolgu yap, randevu al.", npc: { name: "Diş Hekimi", role: "Dişçi", emoji: "🦷" }, photo: "/scenes/disci.jpg".replace("  disci","  3845810"), xp: 85, examples: ["Dişim ağrıyor", "Randevu alabilir miyim?", "Dolgu yapar mısınız?"] },
  { id: "saglik-psikolog", category: "saglik", categoryEmoji: "🏥", title: "Psikolog", emoji: "🧠", location: "Terapi — Seans", description: "Duygularını anlat, rahatla, tavsiye al.", npc: { name: "Psikolog", role: "Psikolog", emoji: "🧠" }, photo: "https://images.pexels.com/photos/ psikolog/pexels-photo-psikolog.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  psikolog","  4101143"), xp: 90, examples: ["Kendimi gergin hissediyorum", "Tavsiyeniz nedir?", "Bir şey anlatmak istiyorum"] },

  // 7. ULAŞIM & SEYAHAT (6 sahne)
  { id: "ulasim-otobus", category: "ulasim", categoryEmoji: "✈️", title: "Otobüs / Dolmuş", emoji: "🚌", location: "Otobüs — Durak", description: "Bilet al, ineceğim de, yer ver.", npc: { name: "Şoför", role: "Şoför", emoji: "👨‍✈️" }, photo: "/scenes/ulasim-otobus.jpg".replace("  otobus","   coach/pexels-photo-coach.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  coach","  117844")), xp: 80, examples: ["Bilet ne kadar?", "Müsait yerde ineceğim", "Yer verir misiniz?"] },
  { id: "ulasim-taksi", category: "ulasim", categoryEmoji: "✈️", title: "Taksi", emoji: "🚕", location: "Taksi — Arka Koltuk", description: "Gündem muhabbeti, şoförle sohbet, bahşiş ver.", npc: { name: "Taksici", role: "Taksici", emoji: "🚕" }, photo: "/scenes/ulasim-taksi.jpg".replace("  taksi","  7681122"), xp: 80, examples: ["Taksim'e gider misiniz?", "Taksi ne kadar tuttu?", "Bozuk var mı?"] },
  { id: "ulasim-tren", category: "ulasim", categoryEmoji: "✈️", title: "Tren / Vapur", emoji: "🚆", location: "Tren — Kompartıman", description: "Bilet kontrol, cam kenarı, varış sor.", npc: { name: "Kondüktör", role: "Kondüktör", emoji: "🎫" }, photo: "/scenes/ulasim-tren.jpg".replace("  tren","  302428"), xp: 85, examples: ["Biletinizi görebilir miyim?", "Cam kenarı boş mu?", "Kaçta varırız?"] },
  { id: "ulasim-ucak", category: "ulasim", categoryEmoji: "✈️", title: "Uçak Kabini", emoji: "✈️", location: "Uçak — Koltuk", description: "Hostesten battaniye iste, kemer bağla, film izle.", npc: { name: "Hostes", role: "Hostes", emoji: "👩‍✈️" }, photo: "https://images.pexels.com/photos/ ucak/pexels-photo-ucak.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  ucak","  723009"), xp: 90, examples: ["Battaniye verir misiniz?", "Kemerimi bağladım", "Film var mı?"] },
  { id: "ulasim-otogar", category: "ulasim", categoryEmoji: "✈️", title: "Otogar / Gar", emoji: "🏢", location: "Otogar — Peron", description: "Peron sor, bagaj ver, rötar sor.", npc: { name: "Görevli", role: "Görevli", emoji: "👨‍💼" }, photo: "https://images.pexels.com/photos/ otogar/pexels-photo-otogar.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  otogar","   378214"), xp: 80, examples: ["Peron kaç?", "Bagajımı vereceğim", "Rötar var mı?"] },
  { id: "ulasim-havalimani", category: "ulasim", categoryEmoji: "✈️", title: "Havalimanı Salon", emoji: "🛫", location: "Havalimanı — Bekleme", description: "Kapı sor, rötar anonsu, duty free gez.", npc: { name: "Görevli", role: "Görevli", emoji: "🛃" }, photo: "https://images.pexels.com/photos/2305097/pexels-photo-2305097.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200", xp: 85, examples: ["Kapı nerede?", "Rötar var mı?", "Duty free nerede?"] },

  // 8. SOSYAL & KÜLTÜREL (7 sahne)
  { id: "sosyal-parti", category: "sosyal", categoryEmoji: "🎉", title: "Parti / Doğum Günü", emoji: "🎂", location: "Ev — Parti", description: "Hediye ver, iyi dilek söyle, dans et.", npc: { name: "Arkadaş", role: "Arkadaş", emoji: "🎉" }, photo: "https://images.pexels.com/photos/ parti/pexels-photo-parti.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  parti","  1190298"), xp: 85, examples: ["İyi ki doğdun!", "Hediyemi beğendin mi?", "Dans edelim mi?"] },
  { id: "sosyal-dugun", category: "sosyal", categoryEmoji: "🎉", title: "Düğün / Nişan", emoji: "💍", location: "Düğün Salonu — Masa", description: "Takı tak, halay çek, tebrik et.", npc: { name: "Damat", role: "Damat", emoji: "🤵" }, photo: "https://images.pexels.com/photos/ dugun/pexels-photo-dugun.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  dugun","  1114425"), xp: 90, examples: ["Tebrik ederim!", "Halay çekelim mi?", "Takı nereye takılır?"] },
  { id: "sosyal-taziye", category: "sosyal", categoryEmoji: "🎉", title: "Taziye Evi", emoji: "🕯️", location: "Taziye — Salon", description: "Başsağlığı dile, fısıltıyla konuş, dua et.", npc: { name: "Taziye Sahibi", role: "Ev Sahibi", emoji: "🕯️" }, photo: "https://images.pexels.com/photos/ taziye/pexels-photo-taziye.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  taziye","  4553613"), xp: 90, examples: ["Başınız sağ olsun", "Allah rahmet eylesin", "Sabır dilerim"] },
  { id: "sosyal-sinema", category: "sosyal", categoryEmoji: "🎉", title: "Sinema Fuaye", emoji: "🎬", location: "Sinema — Fuaye", description: "Film yorumla, mısır al, bilet yırt.", npc: { name: "Arkadaş", role: "Arkadaş", emoji: "🎬" }, photo: "/scenes/sinema.jpg".replace("  sinema2","  436413"), xp: 80, examples: ["Film nasıldı?", "Mısır alır mısın?", "Biletler bende"] },
  { id: "sosyal-konser", category: "sosyal", categoryEmoji: "🎉", title: "Konser / Festival", emoji: "🎤", location: "Festival — Çadır", description: "Bilet göster, sahne sor, tezahürat yap.", npc: { name: "Görevli", role: "Görevli", emoji: "🎤" }, photo: "https://images.pexels.com/photos/ konser/pexels-photo-konser.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  konser","  1105666"), xp: 85, examples: ["Sahne nerede?", "Biletimi göstereyim mi?", "Harikaydı değil mi?"] },
  { id: "sosyal-muze", category: "sosyal", categoryEmoji: "🎉", title: "Müze / Galeri", emoji: "🖼️", location: "Müze — Salon", description: "Eser yorumla, rehber dinle, fotoğraf çekme.", npc: { name: "Rehber", role: "Müze Rehberi", emoji: "🖼️" }, photo: "/scenes/muze.jpg".replace("  muze","  2372979"), xp: 85, examples: ["Bu eser ne anlatıyor?", "Fotoğraf çekebilir miyim?", "Rehber var mı?"] },
  { id: "sosyal-tiyatro", category: "sosyal", categoryEmoji: "🎉", title: "Tiyatro Kulis", emoji: "🎭", location: "Tiyatro — Kulis", description: "Oyun yorumla, kuliste sohbet, alkışla.", npc: { name: "Oyuncu", role: "Oyuncu", emoji: "🎭" }, photo: "/scenes/tiyatro.jpg".replace("  tiyatro","  7991585"), xp: 85, examples: ["Oyun nasıldı?", "Kuliste bekleyebilir miyim?", "Çok beğendim!"] },

  // 9. SPOR & HOBİ (5 sahne)
  { id: "spor-stadyum", category: "spor", categoryEmoji: "⚽", title: "Stadyum Tribün", emoji: "🏟️", location: "Stadyum — Tribün", description: "Tezahürat yap, skor sor, atkı al.", npc: { name: "Taraftar", role: "Taraftar", emoji: "⚽" }, photo: "https://images.pexels.com/photos/ stadyum/pexels-photo-stadyum.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  stadyum","  46798"), xp: 85, examples: ["Gol! Gol!", "Skor ne?", "Atkı ne kadar?"] },
  { id: "spor-gym", category: "spor", categoryEmoji: "⚽", title: "Spor Salonu", emoji: "💪", location: "Gym — Alet", description: "Hoca motive et, set sor, su iste.", npc: { name: "Hoca", role: "Antrenör", emoji: "🏋️" }, photo: "/scenes/spor.jpg", xp: 80, examples: ["Kaç set kaldı?", "Su verir misin?", "Beni çalıştırır mısın?"] },
  { id: "spor-piknik", category: "spor", categoryEmoji: "⚽", title: "Piknik Alanı", emoji: "🧺", location: "Park — Piknik", description: "Mangal yak, top oyna, şarkı söyle.", npc: { name: "Arkadaş", role: "Arkadaş", emoji: "🧺" }, photo: "/scenes/park.jpg".replace("  piknik","  3184183"), xp: 80, examples: ["Mangalı yakar mısın?", "Topu atar mısın?", "Şarkı söyler misin?"] },
  { id: "spor-balik", category: "spor", categoryEmoji: "⚽", title: "Balık Tutma", emoji: "🎣", location: "Sahil — İskele", description: "Olta at, yem tak, balık tut, sohbet et.", npc: { name: "Balıkçı", role: "Balıkçı", emoji: "🎣" }, photo: "https://images.pexels.com/photos/ balik/pexels-photo-balik.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  balik","  294674"), xp: 75, examples: ["Olta atar mısın?", "Yem takar mısın?", "Balık tuttun mu?"] },
  { id: "spor-hobi", category: "spor", categoryEmoji: "⚽", title: "Hobi Atölyesi", emoji: "🎨", location: "Atölye — Seramik", description: "Çamur yoğur, fırınla, boya yap.", npc: { name: "Usta", role: "Hobi Ustası", emoji: "🎨" }, photo: "https://images.pexels.com/photos/ hobi/pexels-photo-hobi.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  hobi","  1047540"), xp: 80, examples: ["Çamuru yoğurur musun?", "Fırınlar mısın?", "Hangi renk boyayayım?"] },

  // 10. DİNİ & MANEVİ (3 sahne)
  { id: "dini-cami", category: "dini", categoryEmoji: "🕌", title: "Cami", emoji: "🕌", location: "Cami — Avlu", description: "Abdest al, namaz kıl, vaaz dinle, sohbet et.", npc: { name: "İmam", role: "İmam", emoji: "🕌" }, photo: "https://images.pexels.com/photos/ cami/pexels-photo-cami.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  cami","  1533683"), xp: 85, examples: ["Abdest nerede alınıyor?", "Namaz kaçta?", "Vaaz ne zaman?"] },
  { id: "dini-dernek", category: "dini", categoryEmoji: "🕌", title: "Dernek / Cem Evi", emoji: "🏠", location: "Dernek — Salon", description: "Çay iç, sohbet et, bağış yap.", npc: { name: "Dernek Başkanı", role: "Başkan", emoji: "🤝" }, photo: "https://images.pexels.com/photos/ dernek/pexels-photo-dernek.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  dernek","  3184296"), xp: 80, examples: ["Çay içer misiniz?", "Bağış yapabilir miyim?", "Sohbet ne zaman?"] },
  { id: "dini-kuran", category: "dini", categoryEmoji: "🕌", title: "Kuran Kursu", emoji: "📖", location: "Kurs — Sınıf", description: "Ders dinle, ezber yap, teneffüste sohbet.", npc: { name: "Hoca", role: "Hoca", emoji: "👨‍🏫" }, photo: "https://images.pexels.com/photos/ kuran/pexels-photo-kuran.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  kuran","  5212345"), xp: 80, examples: ["Ezberimi dinler misiniz?", "Teneffüs kaçta?", "Ders ne zaman?"] },

  // 11. DİJİTAL & SANAL (5 sahne)
  { id: "dijital-telefon", category: "dijital", categoryEmoji: "💻", title: "Telefon Görüşmesi", emoji: "📞", location: "Telefon — Birebir", description: "Ara, aç, meşgule at, konferansa al.", npc: { name: "Arkadaş", role: "Arkadaş", emoji: "📞" }, photo: "https://images.pexels.com/photos/ telefon2/pexels-photo-telefon2.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  telefon2","  1092644"), xp: 80, examples: ["Alo, müsait misin?", "Seni duyamıyorum", "Konferansa alayım mı?"] },
  { id: "dijital-zoom", category: "dijital", categoryEmoji: "💻", title: "Görüntülü Görüşme", emoji: "💻", location: "Zoom — Toplantı", description: "Kamerayı aç, mikrofonu kapat, ekran paylaş.", npc: { name: "Müdür", role: "Yönetici", emoji: "💻" }, photo: "https://images.pexels.com/photos/ zoom/pexels-photo-zoom.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  zoom","  4226123"), xp: 85, examples: ["Kameram açık mı?", "Mikrofonu kapatır mısın?", "Ekranımı paylaşayım mı?"] },
  { id: "dijital-sesli", category: "dijital", categoryEmoji: "💻", title: "Sesli Mesaj", emoji: "🎙️", location: "WhatsApp — Sesli Not", description: "Sesli not at, dinle, cevap ver.", npc: { name: "Arkadaş", role: "Arkadaş", emoji: "🎙️" }, photo: "https://images.pexels.com/photos/ sesli/pexels-photo-sesli.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  sesli","  5052877"), xp: 75, examples: ["Sesli not atar mısın?", "Dinledin mi?", "Cevap verir misin?"] },
  { id: "dijital-oyun", category: "dijital", categoryEmoji: "💻", title: "Oyun İçi Sohbet", emoji: "🎮", location: "Discord — Party", description: "Takım kur, strateji konuş, tezahürat yap.", npc: { name: "Oyuncu", role: "Takım Kaptanı", emoji: "🎮" }, photo: "https://images.pexels.com/photos/ oyun/pexels-photo-oyun.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  oyun","  3165335"), xp: 80, examples: ["Takım kuralım mı?", "Strateji ne?", "Helal olsun!"] },
  { id: "dijital-yayin", category: "dijital", categoryEmoji: "💻", title: "Canlı Yayın", emoji: "📡", location: "Twitch / YouTube", description: "Yayın aç, chat oku, abone iste.", npc: { name: "Yayıncı", role: "Yayıncı", emoji: "📡" }, photo: "https://images.pexels.com/photos/ yayin/pexels-photo-yayin.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  yayin","  1190297"), xp: 85, examples: ["Yayını beğendiniz mi?", "Chat'e bakar mısın?", "Abone olur musun?"] },

  // 12. MAHALLE & SOKAK (5 sahne)
  { id: "mahalle-bakkal", category: "mahalle", categoryEmoji: "🏘️", title: "Bakkal", emoji: "🏪", location: "Bakkal — Tezgah", description: "Ekmek al, veresiye yazdır, borç sor.", npc: { name: "Bakkal Amca", role: "Bakkal", emoji: "🏪" }, photo: "https://images.pexels.com/photos/ bakkal/pexels-photo-bakkal.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  bakkal","  264636"), xp: 75, examples: ["Ekmek verir misin?", "Veresiye yazar mısın?", "Borcum ne kadar?"] },
  { id: "mahalle-kahvehane", category: "mahalle", categoryEmoji: "🏘️", title: "Kahvehane", emoji: "☕", location: "Kahvehane — Masa", description: "Çay söyle, okey oyna, muhabbet et.", npc: { name: "Kahveci", role: "Kahveci", emoji: "☕" }, photo: "https://images.pexels.com/photos/ kahve/pexels-photo-kahve.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  kahve","  1267320"), xp: 80, examples: ["Çay söyler misin?", "Okey oynayalım mı?", "Hesap ne kadar?"] },
  { id: "mahalle-kirtasiye", category: "mahalle", categoryEmoji: "🏘️", title: "Kırtasiye", emoji: "✏️", location: "Kırtasiye — Raf", description: "Defter al, fotokopi çektir, kalem sor.", npc: { name: "Kırtasiyeci", role: "Esnaf", emoji: "✏️" }, photo: "https://images.pexels.com/photos/ kirtasiye/pexels-photo-kirtasiye.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  kirtasiye","  264509"), xp: 75, examples: ["Defter verir misin?", "Fotokopi çeker misin?", "Kalem ne kadar?"] },
  { id: "mahalle-kapici", category: "mahalle", categoryEmoji: "🏘️", title: "Apartman Görevlisi", emoji: "🧹", location: "Apartman — Giriş", description: "Aidat ver, asansör bozuk de, çöpü ver.", npc: { name: "Kapıcı", role: "Görevli", emoji: "🧹" }, photo: "https://images.pexels.com/photos/ kapici/pexels-photo-kapici.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  kapici","  896106"), xp: 75, examples: ["Aidatı vereyim", "Asansör bozuk", "Çöpü alır mısın?"] },
  { id: "mahalle-park", category: "mahalle", categoryEmoji: "🏘️", title: "Park Bankı", emoji: "🏞️", location: "Park — Bank", description: "Bankta otur, çocukları izle, çekirdek çitle.", npc: { name: "Teyze", role: "Mahalleli", emoji: "👵" }, photo: "https://images.pexels.com/photos/ park2/pexels-photo-park2.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=800".replace("  park2","  1103970"), xp: 75, examples: ["Buraya oturabilir miyim?", "Çocuklar çok tatlı", "Çekirdek yer misin?"] },
];
